version: '3.8'

services:
  fta-fmea:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    container_name: fta-fmea
    environment:
      BASE_API_URL: http://localhost:9999/
      REACT_APP_ADMIN_REGISTRATION_ONLY: false
      CONTEXT: fta-fmea
    ports:
      - "8080:80"


  fta-fmea-server:
    build:
      context: deploy/fta-fmea
      dockerfile: deploy/Dockerfile
    container_name: fta-fmea-server
    ports:
      - "9999:8080"
    depends_on:
      - graphdb
    environment:
      REPOSITORY_URL: http://graphdb:7200/repositories/fta-fmea


  graphdb:
    build:
      context: ..
      dockerfile: deploy/db-server/Dockerfile
    container_name: graphdb
    ports:
      - "7200:7200"