version: '3.8'

services:
  fta-fmea:
    image: ghcr.io/kbss-cvut/fta-fmea-ui:latest
    ports:
      - "8080:80"
    depends_on:
      - fta-fmea-server


  fta-fmea-server:
    image: ghcr.io/kbss-cvut/fta-fmea:latest
    ports:
      - "9999:9999"
    depends_on:
      - db-server
    environment:
      REPOSITORY_URL: ${REPOSITORY_URL:-http://db-server:7200/repositories/fta-fmea}


  db-server:
    build:
      context: ../shared/db-server
    expose:
      - "7200"
    ports:
      - "7200:7200"
    restart: always
    volumes:
      - db-server:/opt/graphdb/home

volumes:
  db-server:
